apiVersion: apps/v1
kind: Deployment
metadata:
  name: clone-youtube-stylex-fe
spec:
  selector:
    matchLabels:
      app: clone-youtube-stylex-fe
  template:
    metadata:
      labels:
        app: clone-youtube-stylex-fe
    spec:
      containers:
      - name: clone-youtube-stylex-fe
        image: mushroomgead/clone-youtube-stylex-fe:1.0.3
        envFrom:
          - configMapRef:
              name: clone-youtube-stylex-fe-env
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clone-youtube-stylex-fe-env
data:
  NEXT_PUBLIC_API_ENDPOINT: "localhost"
  NEXT_PUBLIC_API_KEY: "xxxxxxxxxx"
---
apiVersion: v1
kind: Service
metadata:
  name: clone-youtube-stylex-fe
spec:
  type: ClusterIP
  selector:
    app: clone-youtube-stylex-fe
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clone-youtube-stylex-fe-ingress
  annotations:
    nginx.ingress.kubernates.io/rewrite-target: /
  labels:
    name: clone-youtube-stylex-fe-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "hadeshaven.catterydoubleg.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: clone-youtube-stylex-fe
            port: 
              number: 3000


